# Generated by Django 3.1.2 on 2020-10-26 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tugas2', '0002_mengemas_tgl_kemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='tgl_masuk',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
